# backend/langchain_engine/feature_descriptions.py
#
# Plain-language descriptions for the firm-characteristic and macro
# features used by the model. Used to translate SHAP feature codes into
# language a non-technical reader can follow, and to build RAG queries
# against the financial-concepts vector store.

FEATURE_DESCRIPTIONS = {
    "mvel1": "market capitalization (company size)",
    "beta": "sensitivity to overall market movements (beta)",
    "betasq": "squared market beta (extreme market sensitivity)",
    "chmom": "change in 6-month price momentum",
    "dolvol": "average dollar trading volume (liquidity)",
    "idiovol": "stock-specific volatility not explained by the market",
    "indmom": "industry peer momentum",
    "mom1m": "1-month price momentum",
    "mom6m": "6-month price momentum",
    "mom12m": "12-month price momentum",
    "mom36m": "3-year price momentum/reversal",
    "pricedelay": "how slowly the price reacts to market-wide news",
    "turn": "share turnover (trading activity relative to shares outstanding)",
    "absacc": "magnitude of accounting accruals",
    "acc": "accounting accruals (non-cash earnings)",
    "age": "years since the firm went public",
    "agr": "year-over-year asset growth",
    "bm": "book-to-market ratio (a value signal)",
    "bm_ia": "book-to-market ratio relative to industry peers",
    "cashdebt": "operating cash flow relative to total debt",
    "cashpr": "cash productivity (value minus assets, scaled by cash)",
    "cfp": "cash flow to price ratio",
    "cfp_ia": "cash flow to price relative to industry peers",
    "chatoia": "change in asset-turnover efficiency vs. industry",
    "chcsho": "change in shares outstanding (dilution or buybacks)",
    "chempia": "change in employee headcount vs. industry",
    "chinv": "change in inventory levels",
    "chpmia": "change in profit margin vs. industry",
    "convind": "presence of convertible debt or preferred stock",
    "currat": "current ratio (short-term liquidity)",
    "depr": "depreciation relative to gross fixed assets",
    "divi": "dividend initiation",
    "divo": "dividend omission",
    "dy": "dividend yield",
    "egr": "growth in shareholder book equity",
    "ep": "earnings-to-price ratio (a value signal)",
    "gma": "gross profitability (gross profit / assets)",
    "grcapx": "growth in capital expenditures",
    "grltnoa": "growth in long-term net operating assets",
    "herf": "industry concentration",
    "hire": "employee growth rate",
    "invest": "combined growth in capex and inventory",
    "lev": "financial leverage (debt relative to assets)",
    "lgr": "growth in long-term debt",
    "mve_ia": "company size relative to industry peers",
    "operprof": "operating profitability relative to equity",
    "orgcap": "organizational capital (accumulated intangible value)",
    "pchcapx_ia": "percent change in capex vs. industry",
    "pchcurrat": "percent change in current ratio",
    "pchdepr": "percent change in depreciation",
    "pchgm_pchsale": "gross margin growth vs. sales growth",
    "pchquick": "percent change in quick ratio",
    "pchsale_pchinvt": "sales growth vs. inventory growth",
    "pchsale_pchrect": "sales growth vs. receivables growth",
    "pchsale_pchxsga": "sales growth vs. SG&A expense growth",
    "pchsaleinv": "percent change in sales-to-inventory ratio",
    "pctacc": "accruals scaled by absolute earnings",
    "ps": "Piotroski F-score (financial strength composite)",
    "quick": "quick ratio (liquid assets vs. current liabilities)",
    "rd": "significant increase in R&D spending",
    "rd_mve": "R&D spending relative to market value",
    "rd_sale": "R&D spending relative to revenue",
    "realestate": "real estate holdings relative to assets",
    "roic": "return on invested capital",
    "salecash": "sales relative to cash holdings",
    "saleinv": "sales relative to inventory (efficiency)",
    "salerec": "sales relative to accounts receivable",
    "secured": "proportion of debt that is collateralized",
    "securedind": "presence of secured debt",
    "sgr": "year-over-year sales growth",
    "sin": "operates in a 'sin' industry (tobacco, alcohol, gaming)",
    "sp": "sales-to-price ratio",
    "tang": "asset tangibility (physical vs. intangible assets)",
    "tb": "ratio of taxable income to book income",
    "aeavol": "abnormal trading volume around earnings announcements",
    "cash": "cash holdings relative to assets",
    "chtx": "change in income tax expense",
    "cinvest": "recent capital investment relative to historical norms",
    "ear": "stock return around the latest earnings announcement",
    "nincr": "number of consecutive quarters of earnings growth",
    "roaq": "quarterly return on assets",
    "roavol": "volatility of return on assets",
    "roeq": "quarterly return on equity",
    "rsup": "revenue surprise vs. trend",
    "stdacc": "volatility of accounting accruals",
    "stdcf": "volatility of operating cash flow",
    "ms": "Mohanram score (financial strength for growth firms)",
    "baspread": "bid-ask spread (trading cost)",
    "ill": "illiquidity (price impact of trading volume)",
    "maxret": "highest single-day return in the past month",
    "retvol": "daily return volatility over the past month",
    "std_dolvol": "volatility of daily dollar trading volume",
    "std_turn": "volatility of daily share turnover",
    "zerotrade": "frequency of days with no trading activity",
    "macro_dp": "market-wide dividend-to-price ratio",
    "macro_ep": "market-wide earnings-to-price ratio",
    "macro_bm": "market-wide book-to-market ratio",
    "macro_ntis": "net equity issuance across the market",
    "macro_tbl": "short-term Treasury bill rate",
    "macro_tms": "term spread (long-term vs. short-term bond yields)",
    "macro_dfy": "default spread (credit risk conditions)",
    "macro_svar": "overall stock market volatility",
}


def describe_feature(feature_code: str) -> str:
    """Return a plain-language description for a feature code, falling back to the code itself."""
    return FEATURE_DESCRIPTIONS.get(feature_code, feature_code.replace("_", " "))
