import { useState, useEffect, useRef } from "react";
import { gsap } from "gsap";
import { analyzeFeatures } from "./api";

function App() {
  // ---------- REFS FOR GSAP ----------
  const heroRef = useRef(null);
  const controlsRef = useRef(null);
  const resultsRef = useRef(null);

  // ---------- USER INPUT (INTENT, NOT FEATURES) ----------
  const [scenario, setScenario] = useState("neutral");
  const [risk, setRisk] = useState(0.5);
  const [horizon, setHorizon] = useState(12);

  // ---------- STATE ----------
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);

  // ---------- GSAP: PAGE ENTRY ----------
  useEffect(() => {
    const tl = gsap.timeline();

    tl.fromTo(
      heroRef.current,
      { opacity: 0, y: -40 },
      { opacity: 1, y: 0, duration: 0.7, ease: "power3.out" }
    ).fromTo(
      controlsRef.current,
      { opacity: 0, y: 20 },
      { opacity: 1, y: 0, duration: 0.6, ease: "power3.out" },
      "-=0.3"
    );

    return () => tl.kill();
  }, []);

  // ---------- GSAP: RESULTS ENTRY ----------
  useEffect(() => {
    if (!result || !resultsRef.current) return;

    gsap.fromTo(
      resultsRef.current.children,
      { opacity: 0, y: 20 },
      {
        opacity: 1,
        y: 0,
        duration: 0.5,
        stagger: 0.12,
        ease: "power2.out",
      }
    );
  }, [result]);

  // ---------- ANALYZE ----------
  const handleAnalyze = async () => {
    setLoading(true);
    setError(null);

    try {
      const res = await analyzeFeatures({
        scenario,
        risk,
        horizon,
      });
      setResult(res);
    } catch (e) {
      setError(e.message || "Backend request failed");
    } finally {
      setLoading(false);
    }
  };

  // ---------- DERIVED VALUES ----------
  const isOutperform = result?.prediction === 1;
  const confidence = result ? Math.max(...result.probabilities) : 0;
  const maxAbsShap = result
    ? Math.max(...result.top_features.map((f) => f.abs_shap), 1e-9)
    : 1;

  return (
    <div style={styles.page}>
      <div style={styles.container}>
        {/* ---------- HERO ---------- */}
        <header ref={heroRef} style={styles.header}>
          <span style={styles.eyebrow}>AI-Powered Equity Analysis</span>
          <h1 style={styles.title} className="gradient-text">
            FinTech GenAI Analyzer
          </h1>
          <p style={styles.subtitle}>
            CatBoost predictions, SHAP feature attribution, and
            RAG-grounded explanations generated by Llama&nbsp;3.1.
          </p>
        </header>

        {/* ---------- CONTROLS ---------- */}
        <div ref={controlsRef} className="card" style={styles.controls}>
          <div style={styles.controlsGrid}>
            <div style={styles.controlBlock}>
              <label style={styles.label}>Scenario</label>
              <select
                value={scenario}
                onChange={(e) => setScenario(e.target.value)}
                style={styles.fullWidth}
              >
                <option value="conservative">Conservative</option>
                <option value="neutral">Neutral</option>
                <option value="aggressive">Aggressive</option>
              </select>
            </div>

            <div style={styles.controlBlock}>
              <label style={styles.label}>
                Risk Level
                <span style={styles.labelValue}>{risk.toFixed(2)}</span>
              </label>
              <input
                type="range"
                min="0"
                max="1"
                step="0.05"
                value={risk}
                onChange={(e) => setRisk(Number(e.target.value))}
                style={{ "--fill": `${risk * 100}%` }}
              />
              <div style={styles.sliderTicks}>
                <span>Low</span>
                <span>High</span>
              </div>
            </div>

            <div style={styles.controlBlock}>
              <label style={styles.label}>Investment Horizon</label>
              <div style={styles.inputWithUnit}>
                <input
                  type="number"
                  min="1"
                  max="60"
                  value={horizon}
                  onChange={(e) => setHorizon(Number(e.target.value))}
                  style={{ ...styles.fullWidth, paddingRight: 64 }}
                />
                <span style={styles.unit}>months</span>
              </div>
            </div>
          </div>

          <button
            onClick={handleAnalyze}
            disabled={loading}
            style={styles.analyzeButton}
          >
            {loading && <span className="spinner" />}
            {loading ? "Analyzing..." : "Run Analysis"}
          </button>

          {error && <div style={styles.errorBox}>{error}</div>}
        </div>

        {/* ---------- RESULTS ---------- */}
        {result && (
          <div
            ref={resultsRef}
            className="results-grid"
            style={styles.resultsWrap}
          >
            {/* Prediction */}
            <section className="card full-width" style={styles.card}>
              <h2 style={styles.cardTitle}>Model Prediction</h2>
              <div style={styles.predictionRow}>
                <span
                  style={{
                    ...styles.predictionBadge,
                    background: isOutperform
                      ? "rgba(63, 185, 80, 0.15)"
                      : "rgba(248, 81, 73, 0.15)",
                    color: isOutperform ? "#3fb950" : "#f85149",
                    border: `1px solid ${
                      isOutperform ? "#3fb950" : "#f85149"
                    }`,
                  }}
                >
                  {isOutperform ? "Outperformance" : "Underperformance"}
                </span>

                <div style={styles.confidenceWrap}>
                  <div style={styles.confidenceLabel}>
                    <span>Confidence</span>
                    <span style={styles.confidenceValue}>
                      {(confidence * 100).toFixed(1)}%
                    </span>
                  </div>
                  <div style={styles.barTrack}>
                    <div
                      style={{
                        ...styles.barFill,
                        width: `${confidence * 100}%`,
                        background: isOutperform ? "#3fb950" : "#f85149",
                      }}
                    />
                  </div>
                </div>
              </div>

              <div style={styles.probGrid}>
                <div style={styles.probItem}>
                  <span style={styles.probLabel}>Underperform</span>
                  <span style={styles.probValue}>
                    {(result.probabilities[0] * 100).toFixed(1)}%
                  </span>
                </div>
                <div style={{ ...styles.probItem, alignItems: "flex-end" }}>
                  <span style={styles.probLabel}>Outperform</span>
                  <span style={styles.probValue}>
                    {(result.probabilities[1] * 100).toFixed(1)}%
                  </span>
                </div>
              </div>
            </section>

            {/* SHAP feature bars */}
            <section className="card" style={styles.card}>
              <h2 style={styles.cardTitle}>Top Contributing Factors</h2>
              <div style={styles.featureList}>
                {result.top_features.map((f, i) => {
                  const positive = f.shap_value > 0;
                  const pct = (f.abs_shap / maxAbsShap) * 100;
                  return (
                    <div key={i} style={styles.featureRow}>
                      <div style={styles.featureHeader}>
                        <span style={styles.featureName}>{f.feature}</span>
                        <span
                          style={{
                            ...styles.featureValue,
                            color: positive ? "#3fb950" : "#f85149",
                          }}
                        >
                          {positive ? "+" : ""}
                          {f.shap_value.toFixed(4)}
                        </span>
                      </div>
                      <div style={styles.barTrack}>
                        <div
                          style={{
                            ...styles.barFill,
                            width: `${pct}%`,
                            background: positive ? "#3fb950" : "#f85149",
                          }}
                        />
                      </div>
                    </div>
                  );
                })}
              </div>
            </section>

            {/* SHAP summary */}
            <section className="card" style={styles.card}>
              <h2 style={styles.cardTitle}>SHAP Summary</h2>
              <p style={styles.text}>{result.shap_summary}</p>
            </section>

            {/* AI explanation */}
            <section
              className="card full-width"
              style={{ ...styles.card, ...styles.aiCard }}
            >
              <h2 style={styles.cardTitle}>AI-Generated Explanation</h2>
              <p style={styles.text}>{result.llm_explanation}</p>
            </section>
          </div>
        )}

        {/* ---------- FOOTER ---------- */}
        <footer style={styles.footer}>
          <p style={{ margin: 0 }}>
            Predictions are for informational purposes only and do not
            constitute financial advice.
          </p>
          <p style={{ margin: "8px 0 0" }}>Created by Rohit Aralikatti</p>
        </footer>
      </div>
    </div>
  );
}

// ---------- STYLES ----------
const styles = {
  page: {
    minHeight: "100vh",
    padding: "56px 24px",
  },
  container: {
    maxWidth: 980,
    margin: "0 auto",
    fontFamily: "Inter, system-ui, sans-serif",
  },
  header: {
    textAlign: "center",
    marginBottom: 40,
  },
  eyebrow: {
    display: "inline-block",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#58a6ff",
    background: "rgba(88, 166, 255, 0.1)",
    border: "1px solid rgba(88, 166, 255, 0.3)",
    borderRadius: 999,
    padding: "5px 16px",
    marginBottom: 18,
  },
  title: {
    fontSize: "2.75rem",
    fontWeight: 800,
    margin: "0 0 14px",
    letterSpacing: "-0.02em",
  },
  subtitle: {
    fontSize: "1.05rem",
    color: "#8b949e",
    maxWidth: 580,
    margin: "0 auto",
    lineHeight: 1.6,
  },
  controls: {
    padding: 28,
    background: "#161b22",
    border: "1px solid #30363d",
    borderRadius: 16,
    boxShadow: "0 8px 24px rgba(0, 0, 0, 0.2)",
  },
  controlsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))",
    gap: 28,
    marginBottom: 28,
  },
  controlBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  label: {
    fontSize: 12,
    fontWeight: 700,
    color: "#8b949e",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    display: "flex",
    justifyContent: "space-between",
  },
  labelValue: {
    color: "#58a6ff",
    fontWeight: 700,
  },
  fullWidth: {
    width: "100%",
  },
  sliderTicks: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 11,
    color: "#6e7681",
  },
  inputWithUnit: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  unit: {
    position: "absolute",
    right: 14,
    color: "#6e7681",
    fontSize: 13,
    pointerEvents: "none",
  },
  analyzeButton: {
    width: "100%",
    padding: "14px 24px",
    fontSize: 15,
    fontWeight: 700,
    background: "linear-gradient(135deg, #58a6ff, #3b82f6)",
    border: "none",
    color: "#ffffff",
    borderRadius: 10,
    cursor: "pointer",
    boxShadow: "0 4px 14px rgba(88, 166, 255, 0.35)",
  },
  errorBox: {
    marginTop: 16,
    padding: "12px 16px",
    background: "rgba(248, 81, 73, 0.1)",
    border: "1px solid rgba(248, 81, 73, 0.4)",
    borderRadius: 8,
    color: "#f85149",
    fontSize: 14,
  },
  resultsWrap: {
    marginTop: 32,
  },
  card: {
    padding: 24,
    background: "#161b22",
    border: "1px solid #30363d",
    borderRadius: 16,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: 700,
    marginBottom: 18,
    color: "#e6edf3",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  predictionRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 24,
    marginBottom: 20,
  },
  predictionBadge: {
    fontSize: 16,
    fontWeight: 700,
    padding: "10px 22px",
    borderRadius: 10,
    whiteSpace: "nowrap",
  },
  confidenceWrap: {
    flex: 1,
    minWidth: 200,
  },
  confidenceLabel: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 13,
    color: "#8b949e",
    marginBottom: 8,
  },
  confidenceValue: {
    color: "#e6edf3",
    fontWeight: 700,
  },
  barTrack: {
    height: 8,
    background: "#0d1117",
    borderRadius: 4,
    overflow: "hidden",
  },
  barFill: {
    height: "100%",
    borderRadius: 4,
    transition: "width 0.6s ease",
  },
  probGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 16,
    paddingTop: 18,
    borderTop: "1px solid #21262d",
  },
  probItem: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  probLabel: {
    fontSize: 11,
    color: "#8b949e",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  probValue: {
    fontSize: 22,
    fontWeight: 700,
  },
  featureList: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  featureRow: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  featureHeader: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 13,
  },
  featureName: {
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    color: "#e6edf3",
  },
  featureValue: {
    fontWeight: 700,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
  },
  text: {
    color: "#c9d1d9",
    lineHeight: 1.7,
    fontSize: 14.5,
    whiteSpace: "pre-wrap",
    margin: 0,
  },
  aiCard: {
    background:
      "linear-gradient(135deg, rgba(88, 166, 255, 0.06), rgba(63, 185, 80, 0.04))",
    border: "1px solid rgba(88, 166, 255, 0.2)",
  },
  footer: {
    textAlign: "center",
    marginTop: 48,
    fontSize: 12,
    color: "#6e7681",
  },
};

export default App;
